config/urls.py
from django.contrib import admin
from django.urls import path, include
from movies.views import home

urlpatterns = [
    path('admin/', admin.site.urls),
    path('movies/', include('movies.urls')),
    path('', home, name='home' ),
    path('sports/', include('sports.urls')),
    path('music/', include('music.urls')),
    path('travel/', include('travel.urls')),
]

movies/urls.py
from django.urls import path
from . import views


app_name = 'movies'

urlpatterns = [
    path('list/', views.movie_list, name='list'),
    path('create/', views.movie_form, name='create'),
    path('detail/<int:pk>/', views.movie_detail, name='detail'),
    path('update/<int:pk>/', views.movie_update, name='update'),
    path('delete/<int:pk>/', views.movie_delete, name='delete')
]

music/urls.py
from django.urls import path
from . import views


app_name='music'

urlpatterns = [
    path('list', views.music_list, name='list'),
    path('create/', views.music_form, name='create'),
    path('detail/<int:pk>/', views.music_detail, name='detail'),
    path('update/<int:pk>/', views.music_update, name='update'),
    path('delete/<int:pk>/', views.music_delete, name='delete'),
]

movies/models.py
from django.db import models
from django.shortcuts import reverse


class Movie(models.Model):
    title = models.CharField(max_length=100)
    director = models.CharField(max_length=100)
    release_year = models.PositiveIntegerField()
    genre = models.CharField(max_length=100)

    def get_detail_url(self):
        return reverse('movies:detail', args=[self.pk])

    def get_update_url(self):
        return reverse('movies:update', args=[self.pk])

    def get_delete_url(self):
        return reverse('movies:delete', args=[self.pk])

movies/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Movie


def home(request):
    return render(request, 'index.html')

def movie_list(request):
    movies = Movie.objects.all()
    ctx = {'movies': movies}
    return render(request, 'movies/movie-list.html', ctx)

def movie_form(request):
    if request.method == 'POST':
        title = request.POST.get('title')
        director = request.POST.get('director')
        release_year = request.POST.get('release_year')
        genre = request.POST.get('genre')
        if title and director and release_year and genre:
            Movie.objects.create(
                title=title,
                director=director,
                release_year=release_year,
                genre=genre,
            )
            return redirect('movies:list')
    return render(request, 'movies/movie-form.html')

def movie_detail(request, pk):
    movie = get_object_or_404(Movie, pk=pk)
    ctx = {'movie': movie}
    return render(request, 'movies/movie-detail.html', ctx)

def movie_update(request, pk):
    movie = get_object_or_404(Movie, pk=pk)
    if request.method == 'POST':
        title = request.POST.get('title')
        director = request.POST.get('director')
        release_year = request.POST.get('release_year')
        genre = request.POST.get('genre')
        if title and director and release_year and genre:
            movie.title=title
            movie.director=director
            movie.release_year=release_year
            movie.genre=genre
            movie.save()
            return redirect(movie.get_detail_url())
    ctx = {'movie': movie}
    return render(request, 'movies/movie-form.html', ctx)

def movie_delete(request, pk):
    movie = get_object_or_404(Movie, pk=pk)
    movie.delete()
    return redirect('movies:list')

templates/movies/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ movie.title }}</title>
</head>
<body>
<h1>{{ movie.title }}</h1>

<h3><strong>Title:</strong> {{ movie.title }}</h3>
<h3><strong>Director:</strong> {{ movie.director }}</h3>
<h3><strong>Release Year:</strong> {{ movie.release_year }}$</h3>
<h3><strong>Genre:</strong> {{ movie.genre }}$</h3>

<br>
<button><a href="{{ movie.get_update_url }}">Update</a></button> <button><a href="{{ movie.get_delete_url }}">Delete</a></button> <button><a href="{% url 'movies:list' %}">Back to List</a></button>
<br>

</body>
</html>

templates/movies/form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% if movie %}Update Product {% else %}Create Product{% endif %}</title>
</head>
<body>
<h1>{% if movie %}Update Product{% else %}Create Product{% endif %}</h1>
<form method="post">
  {% csrf_token %}
  <label for="title">Title:</label><br>
  <input type="text" name="title" id="title" value="{{ movie.title }}"><br><br>

  <label for="director">Director:</label><br>
  <input type="text" name="director" id="director" value="{{ movie.director }}"><br><br>

  <label for="release_year">Release Year:</label><br>
  <input type="number" name="release_year" id="release_year" value="{{ movie.release_year }}"><br><br>

  <label for="genre">Genre:</label><br>
  <input type="text" name="genre" id="genre" value="{{ movie.genre }}"><br><br>

  {% if movie %}
  <input type="submit" value="Update"><br><br>
      <button><a href="{{ movie.get_detail_url }}">Back to Detail</a></button>
    <br><br>
  {% else %}
   <input type="submit" value="Create Product"><br><br>
    <button><a href="{% url 'movies:list' %}">Back to List</a></button>  <button><a href="{% url 'home' %}">Home</a></button>
    <br><br>
  {% endif %}
</form>

</body>
</html>

templates/movies/list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Movies List</title>
</head>
<body>
    <h1>Movies List</h1>
    <button><a href="{% url 'home' %}">Back to Home</a></button>     <button><a href="{% url 'movies:create' %}">Create Movie</a></button>
    <br>
        {% for movie in movies %}
    <a href="{{ movie.get_detail_url }}"><h3>{{ movie.title }}</h3></a>
        {% empty %}
        <h3>No Created Movies!</h3>
        {% endfor %}
    <h3></h3>
</body>
</html>