config/urls.py
from django.contrib import admin
from django.urls import path, include
from movies.views import home

urlpatterns = [
    path('admin/', admin.site.urls),
    path('movies/', include('movies.urls')),
    path('', home, name='home' ),
    path('sports/', include('sports.urls')),
    path('music/', include('music.urls')),
    path('travel/', include('travel.urls')),
]

music/urls.py
from django.urls import path
from . import views


app_name='music'

urlpatterns = [
    path('list', views.music_list, name='list'),
    path('create/', views.music_form, name='create'),
    path('detail/<int:pk>/', views.music_detail, name='detail'),
    path('update/<int:pk>/', views.music_update, name='update'),
    path('delete/<int:pk>/', views.music_delete, name='delete'),
]

music/models.py
from django.db import models
from django.shortcuts import reverse


class Music(models.Model):
    album_title = models.CharField(max_length=100)
    artist = models.CharField(max_length=100)
    release_date = models.DateField()
    genre = models.CharField(max_length=100)

    def get_detail_url(self):
        return reverse('music:detail', args=[self.pk])

    def get_update_erl(self):
        return reverse('music:update', args=[self.pk])

    def get_delete_url(self):
        return reverse('music:delete', args=[self.pk])

music/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Music


def music_list(request):
    music = Music.objects.all()
    ctx = {'music': music}
    return render(request, 'music/music-list.html', ctx)

def music_form(request):
    if request.method == 'POST':
        album_title = request.POST.get('album_title')
        artist = request.POST.get('artist')
        release_date = request.POST.get('release_date')
        genre = request.POST.get('genre')
        if album_title and artist and release_date and genre:
            Music.objects.create(
                album_title=album_title,
                artist=artist,
                release_date=release_date,
                genre=genre,
            )
            return redirect('music:list')
    return render(request, 'music/music-form.html')

def music_detail(request, pk):
    music = get_object_or_404(Music, pk=pk)
    ctx = {'music': music}
    return render(request, 'music/music-detail.html', ctx)

def music_update(request, pk):
    music = get_object_or_404(Music, pk=pk)
    if request.method == 'POST':
        album_title = request.POST.get('album_title')
        artist = request.POST.get('artist')
        release_date = request.POST.get('release_date')
        genre = request.POST.get('genre')
        if album_title and artist and release_date and genre:
            music.album_title=album_title
            music.artist = artist
            music.release_date = release_date
            music.genre = genre
            music.save()
            return redirect(music.get_detail_url())
    ctx = {'music': music}
    return render(request, 'music/music-form.html', ctx)

def music_delete(request, pk):
    music = get_object_or_404(Music, pk=pk)
    music.delete()
    return redirect('music:list')

templates/music/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ music.album_title }}</title>
</head>
<body>
<h1>{{ music.album_title }}</h1>
     <h3><strong>Artist:</strong>{{ music.artist }}</h3>
     <h3><strong>Release Date:</strong>{{ music.release_date }}</h3>
     <h3><strong>Genre:</strong>{{ music.genre }}</h3>

<button><a href="{{ music.get_update_erl }}">Update</a></button> <button><a href="{{ music.get_delete_url }}">Delete</a></button> <button> <a href="{% url 'music:list' %}">Back to List</a></button>

</body>
</html>

templates/music/form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% if music %}Update Music{% else %} Create Music{% endif %}</title>
</head>
<body>
<h1>{% if music %}Update Music{% else %} Create Music{% endif %}</h1>


<form method="post">
    {% csrf_token %}
    <label for="album_title">Album Title</label><br>
    <input type="text" name="album_title" id="album_title" value="{{ music.album_title }}"><br><br>

    <label for="artist">Artist</label><br>
    <input type="text" name="artist" id="artist" value="{{ music.artist }}"><br><br>

    <label for="release_date">Release Date</label><br>
    <input type="date" name="release_date" id="release_date" value="{{ music.release_date }}"><br><br>

    <label for="genre">Genre</label><br>
    <input type="text" name="genre" id="genre" value="{{ music.genre }}"><br><br>

    {% if music %}
    <input type="submit" value="Update"><br><br>
    <button><a href="{{ music.get_detail_url }}">Back to Detail</a></button>
    <br><br>
    {% else %}
    <input type="submit" value="Create Music"><br><br>
    <button><a href="{% url 'music:list' %}">Back to List</a></button>   <button><a href="{% url 'home' %}">Back to Home</a></button>
<br><br>
    {% endif %}
</form>

</body>
</html>

templates/music/list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Music List</title>
</head>
<body>
<h1>Music List</h1>
    <button><a href="{% url 'music:create' %}">Create Music</a></button>  <button><a href="{% url 'home' %}">Back to Home</a></button>
<br><br>
    {% for music in music %}
<a href="{{ music.get_detail_url }}"><h3>{{ music.album_title }}</h3></a><br>
    {% empty %}
    <h3>No Created Music</h3>
    {% endfor %}
</body>
</html>