config/urls.py
from django.contrib import admin
from django.urls import path, include
from movies.views import home

urlpatterns = [
    path('admin/', admin.site.urls),
    path('movies/', include('movies.urls')),
    path('', home, name='home' ),
    path('sports/', include('sports.urls')),
    path('music/', include('music.urls')),
    path('travel/', include('travel.urls')),
]

music/urls.py
from django.urls import path
from . import views


app_name='music'

urlpatterns = [
    path('list', views.music_list, name='list'),
    path('create/', views.music_form, name='create'),
    path('detail/<int:pk>/', views.music_detail, name='detail'),
    path('update/<int:pk>/', views.music_update, name='update'),
    path('delete/<int:pk>/', views.music_delete, name='delete'),
]

sports/urls.py
from django.urls import path
from . import views


app_name = 'sports'

urlpatterns = [
    path('list/', views.sport_list, name='list'),
    path('create/', views.sport_form, name='create'),
    path('detail/<int:pk>/', views.sport_detail, name='detail'),
    path('update/<int:pk>/', views.sport_update, name='update'),
    path('delete/<int:pk>/', views.sport_delete, name='delete')
]

sports/models.py
from django.db import models
from django.shortcuts import reverse


class Sport(models.Model):
    event_name = models.CharField(max_length=100)
    location = models.CharField(max_length=100)
    date = models.DateField()
    sport_type = models.CharField(max_length=100)

    def get_detail_url(self):
        return reverse('sports:detail', args=[self.pk])

    def get_update_url(self):
        return reverse('sports:update', args=[self.pk])

    def get_delete_url(self):
        return reverse('sports:delete', args=[self.pk])

sports/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Sport


def sport_list(request):
    sports = Sport.objects.all()
    ctx = {'sports': sports}
    return render(request, 'sports/sport-list.html', ctx)

def sport_form(request):
    if request.method == 'POST':
        event_name = request.POST.get('event_name')
        location = request.POST.get('location')
        date = request.POST.get('date')
        sport_type = request.POST.get('sport_type')
        if event_name and location and date and sport_type:
            Sport.objects.create(
                event_name=event_name,
                location=location,
                date=date,
                sport_type=sport_type,
            )
            return redirect('sports:list')
    return  render(request, 'sports/sport-form.html')

def sport_detail(request, pk):
    sport = get_object_or_404(Sport, pk=pk)
    ctx = {'sport':sport}
    return render(request, 'sports/sport-detail.html', ctx)

def sport_update(request, pk):
    sport = get_object_or_404(Sport, pk=pk)
    if request.method == 'POST':
        event_name = request.POST.get('event_name')
        location = request.POST.get('location')
        date = request.POST.get('date')
        sport_type = request.POST.get('sport_type')
        if event_name and location and date and sport_type:
            sport.event_name=event_name
            sport.location=location
            sport.date=date
            sport.sport_type=sport_type
            sport.save()
            return redirect(sport.get_detail_url())
    ctx = {'sport': sport}
    return render(request, 'sports/sport-form.html', ctx)

def sport_delete(request, pk):
    sport = get_object_or_404(Sport, pk=pk)
    sport.delete()
    return redirect('sports:list')

templates/sports/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ sport.event_name }}</title>
</head>
<body>
<h1>{{ sport.event_name }}</h1>

<h3><strong>Location:</strong>{{ sport.location }}</h3>
<h3><strong>Date:</strong>{{ sport.date }}</h3>
<h3><strong>Sport Type:</strong>{{ sport.sport_type }}</h3>
<br>
<button><a href="{{ sport.get_update_url }}">Update</a></button>  <button><a href="{{ sport.get_delete_url }}">Delete</a></button>  <button><a href="{% url 'sports:list' %}">Back to List</a></button>
<br>

</body>
</html>

templates/sports/form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% if sport %}Update Sport{% else %}Create Sport{% endif %}</title>
</head>
<body>
<h1>{% if sport %}Update Sport{% else %}Create Sport{% endif %}</h1>


<form method="post">
    {% csrf_token %}
    <label for="event_name">Event Name</label><br>
    <input type="text" name="event_name" id="event_name" value="{{ sport.event_name }}"><br><br>

    <label for="location">Location</label><br>
    <input type="text" name="location" id="location" value="{{ sport.location }}"><br><br>

    <label for="date">Date</label><br>
    <input type="date" name="date" id="date" value="{{ sport.date }}"><br><br>

    <label for="sport_type">Sport Type</label><br>
    <input type="text" name="sport_type" id="sport_type" value="{{ sport.sport_type }}"><br><br>

    {% if sport %}
    <input type="submit" value="Update"><br><br>
    <button><a href="{{ sport.get_detail_url }}">Back to Detail</a></button>
    <br><br>
    {% else %}
    <input type="submit" value="Create Sport"><br><br>
    <button><a href="{% url 'sports:list' %}">Back to List</a></button> <button><a href="{% url 'home' %}">Back to Home</a></button>
<br>
    {% endif %}
</form>


</body>
</html>

templates/sports/list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Sports List</title>
</head>
<body>
<h1>Sports List</h1>
<button><a href="{% url 'home' %}">Back to Home</a></button>   <button><a href="{% url 'sports:create' %}">Create Now Sport</a></button>
    <br><br>
    {% for sport in sports %}
<a href="{{ sport.get_detail_url }}"><h3>{{ sport.event_name }}</h3></a>
    {% empty %}
    <h3>No Created Sports</h3>
    {% endfor %}
</body>
</html>