config/urls.py
from django.contrib import admin
from django.urls import path, include
from movies.views import home

urlpatterns = [
    path('admin/', admin.site.urls),
    path('movies/', include('movies.urls')),
    path('', home, name='home' ),
    path('sports/', include('sports.urls')),
    path('music/', include('music.urls')),
    path('travel/', include('travel.urls')),
]

music/urls.py
from django.urls import path
from . import views


app_name='music'

urlpatterns = [
    path('list', views.music_list, name='list'),
    path('create/', views.music_form, name='create'),
    path('detail/<int:pk>/', views.music_detail, name='detail'),
    path('update/<int:pk>/', views.music_update, name='update'),
    path('delete/<int:pk>/', views.music_delete, name='delete'),
]

travel/urls.py
from django.urls import path
from . import views


app_name='travel'

urlpatterns = [
    path('list/', views.travel_list, name='list'),
    path('create/', views.travel_form, name='create'),
    path('detail/<int:pk>/', views.travel_detail, name='detail'),
    path('update/<int:pk>/', views.travel_update, name='update'),
    path('delete/<int:pk>/', views.travel_delete, name='delete'),
]

travel/models.py
from django.db import models
from django.shortcuts import reverse


class Travel(models.Model):
    destination_name = models.CharField(max_length=100)
    country = models.CharField(max_length=200)
    description = models.TextField()
    popular_season = models.CharField(max_length=200)

    def get_detail_url(self):
        return reverse('travel:detail', args=[self.pk])

    def get_update_url(self):
        return reverse('travel:update', args=[self.pk])

    def get_delete_url(self):
        return reverse('travel:delete', args=[self.pk])

travel/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Travel


def travel_list(request):
    travel = Travel.objects.all()
    ctx = {'travel': travel}
    return render(request, 'travel/travel-list.html', ctx)

def travel_form(request):
    if request.method == 'POST':
        destination_name = request.POST.get('destination_name')
        country = request.POST.get('country')
        description = request.POST.get('description')
        popular_season = request.POST.get('popular_season')
        if destination_name and country and description and popular_season:
            Travel.objects.create(
                destination_name=destination_name,
                country=country,
                description=description,
                popular_season=popular_season
            )
            return redirect('travel:list')
    return render(request, 'travel/travel-form.html')

def travel_detail(request, pk):
    travel = get_object_or_404(Travel, pk=pk)
    ctx = {'travel': travel}
    return render(request, 'travel/travel-detail.html', ctx)

def travel_update(request, pk):
    travel = get_object_or_404(Travel, pk=pk)
    if request.method == 'POST':
        destination_name = request.POST.get('destination_name')
        country = request.POST.get('country')
        description = request.POST.get('description')
        popular_season = request.POST.get('popular_season')
        if destination_name and country and description and popular_season:
            travel.destination_name=destination_name
            travel.country=country
            travel.description=description
            travel.popular_season=popular_season
            travel.save()
            return redirect(travel.get_detail_url())
    ctx = {'travel': travel}
    return render(request, 'travel/travel-form.html', ctx)

def travel_delete(request, pk):
    travel = get_object_or_404(Travel, pk=pk)
    travel.delete()
    return redirect('travel:list')

templates/travel/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ travel.destination_name }}</title>
</head>
<body>
    <h1>{{ travel.destination_name }}</h1>

    <h3><strong>Country: </strong>{{ travel.country }}</h3>
    <h3><strong>Description: </strong>{{ travel.description }}</h3>
    <h3><strong>Popular Season: </strong>{{ travel.popular_season }}</h3>
    <br>
<button><a href="{{ travel.get_update_url }}">Update</a></button> <button><a href="{{ travel.get_delete_url }}">Delete</a></button> <button><a href="{% url 'travel:list' %}">Back to List</a></button>
    <br><br>


</body>
</html>

templates/travel/form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% if travel %}Update Travel{% else %}Create Travel{% endif %}</title>
</head>
<body>
<h1>{% if travel %}Update Travel{% else %}Create Travel{% endif %}</h1>
<form method="post">

    {% csrf_token %}

    <label for="destination_name">Destination Name</label><br>
    <input type="text" name="destination_name" id="destination_name" value="{{ travel.destination_name }}"><br><br>

    <label for="country">Country</label><br>
    <input type="text" name="country" id="country" value="{{ travel.country }}"><br><br>

    <label for="description">Description</label><br>
    <textarea name="description" id="description" cols="30" rows="10">{{ travel.description }}</textarea><br><br>

    <label for="popular_season">Popular Season</label><br>
    <input type="text" name="popular_season" id="popular_season" value="{{ travel.popular_season }}"><br><br>

    {% if travel %}
    <input type="submit" value="Update"><br><br>
    <button><a href="{{ travel.get_detail_url }}">Back to detail</a></button>
    <br><br>
    {% else %}
    <input type="submit" value="Create Travel"><br><br>
    <button><a href="{% url 'travel:list' %}">Back to List</a></button>  <button><a href="{% url 'home' %}">Back to Home</a></button>
    <br><br>
    {% endif %}
</form>

</body>
</html>

templates/travel/list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Travel List</title>
</head>
<body>
<h1>Travel List</h1>
    <button><a href="{% url 'travel:create' %}">Create Travel</a></button> <button><a href="{% url 'home' %}">Back to Home</a></button>
<br><br>
    {% for travel in travel %}
    <a href="{{ travel.get_detail_url }}"><h3>{{ travel.destination_name }}</h3></a>
    {% empty %}
    <h3>No Created Travel</h3>
    {% endfor %}
</body>
</html>